site_name: CloudNativePG 1.29

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - md_in_html

plugins:
  - search

theme:
  name: material
  custom_dir: docs/overrides
  favicon: img/favicon.ico

  logo_dark_mode: 'img/logo-dark.png'
  logo_light_mode: 'img/logo-light.png'

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  generator: false

repo_url: https://github.com/pgEdge/postgresql-docs

nav:
  - CloudNativePG: index.md
  - Appendixes:
    - Appendix B - Backup on object stores: appendixes/backup_barmanobjectstore.md
    - Appendix A - Backup on volume snapshots: appendixes/backup_volumesnapshot.md
    - Appendix C - Common object stores for backups: appendixes/object_stores.md
  - Backup and Recovery: backup_recovery.md
  - Cncf Projects:
    - Cilium: cncf-projects/cilium.md
    - External Secrets: cncf-projects/external-secrets.md
  - Before you start: before_you_start.md
  - Use cases: use_cases.md
  - Architecture: architecture.md
  - Release Notes:
    - EDB Cloud-Native PostgreSQL: release_notes/edb-cloud-native-postgresql.md
    - Old:
      - Release notes for CloudNativePG 1.15: release_notes/old/v1.15.md
      - Release notes for CloudNativePG 1.16: release_notes/old/v1.16.md
      - Release notes for CloudNativePG 1.17: release_notes/old/v1.17.md
      - Release notes for CloudNativePG 1.18: release_notes/old/v1.18.md
      - Release notes for CloudNativePG 1.19: release_notes/old/v1.19.md
      - Release notes for CloudNativePG 1.20: release_notes/old/v1.20.md
      - Release notes for CloudNativePG 1.21: release_notes/old/v1.21.md
      - Release notes for CloudNativePG 1.22: release_notes/old/v1.22.md
      - Release notes for CloudNativePG 1.23: release_notes/old/v1.23.md
      - Release notes for CloudNativePG 1.24: release_notes/old/v1.24.md
      - Release notes for CloudNativePG 1.25: release_notes/old/v1.25.md
      - Release notes for CloudNativePG 1.26: release_notes/old/v1.26.md
    - Release notes for CloudNativePG 1.27: release_notes/v1.27.md
    - Release notes for CloudNativePG 1.28: release_notes/v1.28.md
    - Release notes for CloudNativePG 1.29: release_notes/v1.29.md
  - Installation and upgrades: installation_upgrade.md
  - Quickstart: quickstart.md
  - Image Catalog: image_catalog.md
  - Bootstrap: bootstrap.md
  - Importing Postgres databases: database_import.md
  - Postgres Instance Manager: instance_manager.md
  - Scheduling: scheduling.md
  - Resource management: resource_management.md
  - Failure Modes: failure_modes.md
  - Rolling updates: rolling_update.md
  - Replication: replication.md
  - Logical Replication: logical_replication.md
  - Backup: backup.md
  - WAL archiving: wal_archiving.md
  - Recovery: recovery.md
  - Service management: service_management.md
  - PostgreSQL Configuration: postgresql_conf.md
  - PostgreSQL Role management: declarative_role_management.md
  - PostgreSQL Database management: declarative_database_management.md
  - Tablespaces: tablespaces.md
  - Operator configuration: operator_conf.md
  - Instance Pod configuration: cluster_conf.md
  - Storage: storage.md
  - Labels and Annotations: labels_annotations.md
  - Monitoring: monitoring.md
  - Logging: logging.md
  - Certificates: certificates.md
  - Client TLS/SSL connections: ssl_connections.md
  - Connecting from an application: applications.md
  - Connection Pooling: connection_pooling.md
  - Replica clusters: replica_cluster.md
  - Kubernetes upgrade and maintenance: kubernetes_upgrade.md
  - PostgreSQL upgrades: postgres_upgrades.md
  - Kubectl Plugin: kubectl-plugin.md
  - Automated failover: failover.md
  - Troubleshooting: troubleshooting.md
  - Fencing: fencing.md
  - Declarative hibernation: declarative_hibernation.md
  - PostGIS: postgis.md
  - End-to-End Tests: e2e.md
  - Container Image Requirements: container_images.md
  - Image Volume Extensions: imagevolume_extensions.md
  - CNPG-I: cnpg_i.md
  - Operator capability levels: operator_capability_levels.md
  - Custom Pod Controller: controller.md
  - Examples: samples.md
  - Networking: networking.md
  - Benchmarking: benchmarking.md
  - Frequently Asked Questions (FAQ): faq.md
  - API Reference: cloudnative-pg.v1.md
  - Supported releases: supported_releases.md
  - Preview Versions: preview_version.md
  - Release notes: release_notes.md
