site_name: pg_vectorize v0.26.0

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - md_in_html

plugins:
  - search

theme:
  name: material
  custom_dir: docs/overrides
  favicon: img/favicon.ico

  logo_dark_mode: 'img/logo-dark.png'
  logo_light_mode: 'img/logo-light.png'

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  generator: false

repo_url: https://github.com/pgEdge/postgresql-docs

nav:
  - 'runs Postgres, the embeddings server, and the management API': index.md
  - index:
    - extension/index.md
    - PG Vectorize API Overview: extension/api/index.md
    - Api:
      - RAG: extension/api/rag.md
      - Vector Search: extension/api/search.md
      - Utilities: extension/api/utilities.md
    - Configuring pg_vectorize: extension/configuration.md
    - Examples:
      - Vector Search with OpenAI: extension/examples/openai_embeddings.md
      - Scheduling Embedding Updates: extension/examples/scheduling.md
      - Sentence Transformers: extension/examples/sentence_transformers.md
  - Extension:
    - Supported Transformers and Generative Models: extension/models/index.md
  - index:
    - server/index.md
    - Api:
      - search: server/api/search.md
      - table: server/api/table.md
